In [130]:
import numpy as np 
import pandas as pd

## Exploratory Data Analysis

In [131]:
df = pd.read_csv("../data/laptop_price_dataset.csv")
df

,Company,Product,TypeName,Inches,ScreenResolution,CPU_Company,CPU_Type,CPU_Frequency (GHz),RAM (GB),Memory,GPU_Company,GPU_Type,OpSys,Weight (kg),Price (Euro)
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel,Core i5,2.3,8,128GB SSD,Intel,Iris Plus Graphics 640,macOS,1.37,1339.69
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel,Core i5,1.8,8,128GB Flash Storage,Intel,HD Graphics 6000,macOS,1.34,898.94
2,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel,Core i5 7200U,2.5,8,256GB SSD,Intel,HD Graphics 620,No OS,1.86,575.00
3,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel,Core i7,2.7,16,512GB SSD,AMD,Radeon Pro 455,macOS,1.83,2537.45
4,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel,Core i5,3.1,8,256GB SSD,Intel,Iris Plus Graphics 650,macOS,1.37,1803.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1270,Lenovo,Yoga 500-14ISK,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel,Core i7 6500U,2.5,4,128GB SSD,Intel,HD Graphics 520,Windows 10,1.80,638.00
1271,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel,Core i7 6500U,2.5,16,512GB SSD,Intel,HD Graphics 520,Windows 10,1.30,1499.00
1272,Lenovo,IdeaPad 100S-14IBR,Notebook,14.0,1366x768,Intel,Celeron Dual Core N3050,1.6,2,64GB Flash Storage,Intel,HD Graphics,Windows 10,1.50,229.00
1273,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel,Core i7 6500U,2.5,6,1TB HDD,AMD,Radeon R5 M330,Windows 10,2.19,764.00
1274,Asus,X553SA-XX031T (N3050/4GB/500GB/W10),Notebook,15.6,1366x768,Intel,Celeron Dual Core N3050,1.6,4,500GB HDD,Intel,HD Graphics,Windows 10,2.20,369.00

In [132]:
df.head()

,Company,Product,TypeName,Inches,ScreenResolution,CPU_Company,CPU_Type,CPU_Frequency (GHz),RAM (GB),Memory,GPU_Company,GPU_Type,OpSys,Weight (kg),Price (Euro)
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel,Core i5,2.3,8,128GB SSD,Intel,Iris Plus Graphics 640,macOS,1.37,1339.69
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel,Core i5,1.8,8,128GB Flash Storage,Intel,HD Graphics 6000,macOS,1.34,898.94
2,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel,Core i5 7200U,2.5,8,256GB SSD,Intel,HD Graphics 620,No OS,1.86,575.00
3,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel,Core i7,2.7,16,512GB SSD,AMD,Radeon Pro 455,macOS,1.83,2537.45
4,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel,Core i5,3.1,8,256GB SSD,Intel,Iris Plus Graphics 650,macOS,1.37,1803.60

In [133]:
df.describe

<bound method NDFrame.describe of      Company                              Product            TypeName  Inches  \
0      Apple                          MacBook Pro           Ultrabook    13.3
1      Apple                          Macbook Air           Ultrabook    13.3
2         HP                               250 G6            Notebook    15.6
3      Apple                          MacBook Pro           Ultrabook    15.4
4      Apple                          MacBook Pro           Ultrabook    13.3
...      ...                                  ...                 ...     ...
1270  Lenovo                       Yoga 500-14ISK  2 in 1 Convertible    14.0
1271  Lenovo                       Yoga 900-13ISK  2 in 1 Convertible    13.3
1272  Lenovo                   IdeaPad 100S-14IBR            Notebook    14.0
1273      HP  15-AC110nv (i7-6500U/6GB/1TB/Radeon            Notebook    15.6
1274    Asus  X553SA-XX031T (N3050/4GB/500GB/W10)            Notebook    15.6

                                ScreenResolution CPU_Company  \
0             IPS Panel Retina Display 2560x1600       Intel
1                                       1440x900       Intel
2                              Full HD 1920x1080       Intel
3             IPS Panel Retina Display 2880x1800       Intel
4             IPS Panel Retina Display 2560x1600       Intel
...                                          ...         ...
1270   IPS Panel Full HD / Touchscreen 1920x1080       Intel
1271  IPS Panel Quad HD+ / Touchscreen 3200x1800       Intel
1272                                    1366x768       Intel
1273                                    1366x768       Intel
1274                                    1366x768       Intel

                     CPU_Type  CPU_Frequency (GHz)  RAM (GB)  \
0                     Core i5                  2.3         8
1                     Core i5                  1.8         8
2               Core i5 7200U                  2.5         8
3                     Core i7                  2.7        16
4                     Core i5                  3.1         8
...                       ...                  ...       ...
1270            Core i7 6500U                  2.5         4
1271            Core i7 6500U                  2.5        16
1272  Celeron Dual Core N3050                  1.6         2
1273            Core i7 6500U                  2.5         6
1274  Celeron Dual Core N3050                  1.6         4

                   Memory GPU_Company                GPU_Type       OpSys  \
0               128GB SSD       Intel  Iris Plus Graphics 640       macOS
1     128GB Flash Storage       Intel        HD Graphics 6000       macOS
2               256GB SSD       Intel         HD Graphics 620       No OS
3               512GB SSD         AMD          Radeon Pro 455       macOS
4               256GB SSD       Intel  Iris Plus Graphics 650       macOS
...                   ...         ...                     ...         ...
1270            128GB SSD       Intel         HD Graphics 520  Windows 10
1271            512GB SSD       Intel         HD Graphics 520  Windows 10
1272   64GB Flash Storage       Intel             HD Graphics  Windows 10
1273              1TB HDD         AMD          Radeon R5 M330  Windows 10
1274            500GB HDD       Intel             HD Graphics  Windows 10

      Weight (kg)  Price (Euro)
0            1.37       1339.69
1            1.34        898.94
2            1.86        575.00
3            1.83       2537.45
4            1.37       1803.60
...           ...           ...
1270         1.80        638.00
1271         1.30       1499.00
1272         1.50        229.00
1273         2.19        764.00
1274         2.20        369.00

[1275 rows x 15 columns]>

In [134]:
df.shape

(1275, 15)

In [135]:
df.columns

Index(['Company', 'Product', 'TypeName', 'Inches', 'ScreenResolution',
       'CPU_Company', 'CPU_Type', 'CPU_Frequency (GHz)', 'RAM (GB)', 'Memory',
       'GPU_Company', 'GPU_Type', 'OpSys', 'Weight (kg)', 'Price (Euro)'],
      dtype='str')

In [136]:
df.info

<bound method DataFrame.info of      Company                              Product            TypeName  Inches  \
0      Apple                          MacBook Pro           Ultrabook    13.3
1      Apple                          Macbook Air           Ultrabook    13.3
2         HP                               250 G6            Notebook    15.6
3      Apple                          MacBook Pro           Ultrabook    15.4
4      Apple                          MacBook Pro           Ultrabook    13.3
...      ...                                  ...                 ...     ...
1270  Lenovo                       Yoga 500-14ISK  2 in 1 Convertible    14.0
1271  Lenovo                       Yoga 900-13ISK  2 in 1 Convertible    13.3
1272  Lenovo                   IdeaPad 100S-14IBR            Notebook    14.0
1273      HP  15-AC110nv (i7-6500U/6GB/1TB/Radeon            Notebook    15.6
1274    Asus  X553SA-XX031T (N3050/4GB/500GB/W10)            Notebook    15.6

                                ScreenResolution CPU_Company  \
0             IPS Panel Retina Display 2560x1600       Intel
1                                       1440x900       Intel
2                              Full HD 1920x1080       Intel
3             IPS Panel Retina Display 2880x1800       Intel
4             IPS Panel Retina Display 2560x1600       Intel
...                                          ...         ...
1270   IPS Panel Full HD / Touchscreen 1920x1080       Intel
1271  IPS Panel Quad HD+ / Touchscreen 3200x1800       Intel
1272                                    1366x768       Intel
1273                                    1366x768       Intel
1274                                    1366x768       Intel

                     CPU_Type  CPU_Frequency (GHz)  RAM (GB)  \
0                     Core i5                  2.3         8
1                     Core i5                  1.8         8
2               Core i5 7200U                  2.5         8
3                     Core i7                  2.7        16
4                     Core i5                  3.1         8
...                       ...                  ...       ...
1270            Core i7 6500U                  2.5         4
1271            Core i7 6500U                  2.5        16
1272  Celeron Dual Core N3050                  1.6         2
1273            Core i7 6500U                  2.5         6
1274  Celeron Dual Core N3050                  1.6         4

                   Memory GPU_Company                GPU_Type       OpSys  \
0               128GB SSD       Intel  Iris Plus Graphics 640       macOS
1     128GB Flash Storage       Intel        HD Graphics 6000       macOS
2               256GB SSD       Intel         HD Graphics 620       No OS
3               512GB SSD         AMD          Radeon Pro 455       macOS
4               256GB SSD       Intel  Iris Plus Graphics 650       macOS
...                   ...         ...                     ...         ...
1270            128GB SSD       Intel         HD Graphics 520  Windows 10
1271            512GB SSD       Intel         HD Graphics 520  Windows 10
1272   64GB Flash Storage       Intel             HD Graphics  Windows 10
1273              1TB HDD         AMD          Radeon R5 M330  Windows 10
1274            500GB HDD       Intel             HD Graphics  Windows 10

      Weight (kg)  Price (Euro)
0            1.37       1339.69
1            1.34        898.94
2            1.86        575.00
3            1.83       2537.45
4            1.37       1803.60
...           ...           ...
1270         1.80        638.00
1271         1.30       1499.00
1272         1.50        229.00
1273         2.19        764.00
1274         2.20        369.00

[1275 rows x 15 columns]>

In [137]:
df.isnull().sum()

Company                0
Product                0
TypeName               0
Inches                 0
ScreenResolution       0
CPU_Company            0
CPU_Type               0
CPU_Frequency (GHz)    0
RAM (GB)               0
Memory                 0
GPU_Company            0
GPU_Type               0
OpSys                  0
Weight (kg)            0
Price (Euro)           0
dtype: int64

In [138]:
df.duplicated().sum()

np.int64(0)


### 1. separate numerical and categorical columns 
### 2. inspect categorical variables
### 3. inspect the target vriable 
### 4. Explore numerial features

### 1. Separating numerical and categroical columns

In [139]:
df.select_dtypes(include="number").columns

Index(['Inches', 'CPU_Frequency (GHz)', 'RAM (GB)', 'Weight (kg)',
       'Price (Euro)'],
      dtype='str')

In [140]:
df.select_dtypes(include=["object", "str"]).columns

Index(['Company', 'Product', 'TypeName', 'ScreenResolution', 'CPU_Company',
       'CPU_Type', 'Memory', 'GPU_Company', 'GPU_Type', 'OpSys'],
      dtype='str')

### 2. Inspecting Categroical columns

In [141]:
df["Company"].value_counts()

Company
Dell         291
Lenovo       289
HP           268
Asus         152
Acer         101
MSI           54
Toshiba       48
Apple         21
Samsung        9
Razer          7
Mediacom       7
Microsoft      6
Xiaomi         4
Vero           4
Chuwi          3
Google         3
Fujitsu        3
LG             3
Huawei         2
Name: count, dtype: int64

#### Company

The `Company` feature contains several categories with highly different
frequencies. Dell, Lenovo, and HP are well represented, while several
companies have only a few observations.

We will consider how to handle these rare categories during categorical
encoding and preprocessing.

In [142]:
df["Product"].value_counts()

Product
XPS 13                                       30
Inspiron 3567                                25
250 G6                                       21
Legion Y520-15IKBN                           19
Vostro 3568                                  19
                                             ..
Stream 11-Y000na                              1
X556UJ-XO044T (i7-6500U/4GB/500GB/GeForce     1
Yoga 500-14ISK                                1
15-AC110nv (i7-6500U/6GB/1TB/Radeon           1
X553SA-XX031T (N3050/4GB/500GB/W10)           1
Name: count, Length: 618, dtype: int64

`Product` has high cardinality (618 unique values), with many products appearing only once. This may make direct one-hot encoding inefficient, so its treatment will be considered during feature engineering.

In [143]:
df["TypeName"].value_counts()

TypeName
Notebook              707
Gaming                205
Ultrabook             194
2 in 1 Convertible    117
Workstation            29
Netbook                23
Name: count, dtype: int64

The `TypeName` contains six categories with different frequencies. The feature has relatively low cardinality and can likely be handled using one-hot encoding during preprocessing.

In [144]:
df["ScreenResolution"].value_counts()

ScreenResolution
Full HD 1920x1080                                505
1366x768                                         263
IPS Panel Full HD 1920x1080                      226
IPS Panel Full HD / Touchscreen 1920x1080         51
Full HD / Touchscreen 1920x1080                   47
1600x900                                          23
Touchscreen 1366x768                              16
Quad HD+ / Touchscreen 3200x1800                  15
IPS Panel 4K Ultra HD 3840x2160                   12
IPS Panel 4K Ultra HD / Touchscreen 3840x2160     11
4K Ultra HD / Touchscreen 3840x2160               10
IPS Panel 1366x768                                 7
Touchscreen 2560x1440                              7
4K Ultra HD 3840x2160                              7
IPS Panel Retina Display 2560x1600                 6
IPS Panel Retina Display 2304x1440                 6
Touchscreen 2256x1504                              6
IPS Panel Touchscreen 2560x1440                    5
1440x900                                           4
IPS Panel Retina Display 2880x1800                 4
IPS Panel Touchscreen 1920x1200                    4
IPS Panel 2560x1440                                4
IPS Panel Quad HD+ / Touchscreen 3200x1800         4
Touchscreen 2400x1600                              3
2560x1440                                          3
IPS Panel Quad HD+ 2560x1440                       3
IPS Panel Touchscreen 1366x768                     3
1920x1080                                          3
Quad HD+ 3200x1800                                 3
IPS Panel Full HD 2160x1440                        2
IPS Panel Quad HD+ 3200x1800                       2
IPS Panel Touchscreen / 4K Ultra HD 3840x2160      2
Touchscreen / Quad HD+ 3200x1800                   1
IPS Panel Full HD 1366x768                         1
IPS Panel Full HD 2560x1440                        1
IPS Panel Retina Display 2736x1824                 1
IPS Panel Full HD 1920x1200                        1
Touchscreen / Full HD 1920x1080                    1
Touchscreen / 4K Ultra HD 3840x2160                1
IPS Panel Touchscreen 2400x1600                    1
Name: count, dtype: int64

In [145]:
df["ScreenResolution"].nunique()

40

`ScreenResolution` has relatively high cardinality, but its categorical values contain multiple meaningful attributes such as resolution, panel type, and touchscreen capability. Therefore, directly one-hot encoding the raw feature may not be the most appropriate representation. Feature extraction will be considered during preprocessing.

In [146]:
df["CPU_Company"].value_counts()

CPU_Company
Intel      1214
AMD          60
Samsung       1
Name: count, dtype: int64

`CPU_Company` has only three categories, with Intel being highly dominant. Samsung is extremely rare, appearing only once. Due to its low cardinality, the feature can be handled with one-hot encoding, while the effect of the rare Samsung category should be considered during preprocessing.

In [147]:
df["CPU_Type"].value_counts()

CPU_Type
Core i5 7200U     193
Core i7 7700HQ    147
Core i7 7500U     133
Core i3 6006U      81
Core i7 8550U      73
                 ...
Core M 6Y54         1
Cortex A72&A53      1
E-Series 9000       1
Core M 6Y30         1
A9-Series 9410      1
Name: count, Length: 93, dtype: int64

In [148]:
df["Memory"].value_counts()

Memory
256GB SSD                        412
1TB HDD                          215
500GB HDD                        124
512GB SSD                        114
128GB SSD +  1TB HDD              94
128GB SSD                         74
256GB SSD +  1TB HDD              73
32GB Flash Storage                36
2TB HDD                           16
512GB SSD +  1TB HDD              14
1TB SSD                           14
64GB Flash Storage                13
256GB SSD +  2TB HDD              10
256GB Flash Storage                8
1.0TB Hybrid                       7
16GB Flash Storage                 7
32GB SSD                           6
180GB SSD                          5
128GB Flash Storage                4
16GB SSD                           3
512GB SSD +  2TB HDD               3
256GB SSD +  256GB SSD             2
256GB SSD +  500GB HDD             2
128GB SSD +  2TB HDD               2
1TB SSD +  1TB HDD                 2
512GB Flash Storage                2
64GB SSD                           1
512GB SSD +  512GB SSD             1
512GB SSD +  256GB SSD             1
64GB Flash Storage +  1TB HDD      1
1TB HDD +  1TB HDD                 1
32GB HDD                           1
128GB HDD                          1
240GB SSD                          1
8GB SSD                            1
508GB Hybrid                       1
1.0TB HDD                          1
512GB SSD +  1.0TB Hybrid          1
256GB SSD +  1.0TB Hybrid          1
Name: count, dtype: int64

In [149]:
df["Memory"].nunique()

39

In [150]:
df["GPU_Company"].value_counts()

GPU_Company
Intel     704
Nvidia    396
AMD       174
ARM         1
Name: count, dtype: int64

In [151]:
df["GPU_Type"].value_counts()

GPU_Type
HD Graphics 620     280
HD Graphics 520     181
UHD Graphics 620     68
GeForce GTX 1050     66
GeForce GTX 1060     48
                   ...
Quadro M500M          1
Radeon R7 M360        1
Quadro M3000M         1
GeForce 960M          1
Mali T860 MP4         1
Name: count, Length: 106, dtype: int64

In [152]:
df["OpSys"].value_counts()

OpSys
Windows 10      1048
No OS             66
Linux             58
Windows 7         45
Chrome OS         27
macOS             13
Mac OS X           8
Windows 10 S       8
Android            2
Name: count, dtype: int64

### These cantegorical features can be shown numerically with one-hot encoding :
`Company`
`TypeName`
`CPU_Company`
`GPU_Company`
`OpSys`